apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealdb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mealdb-app
  template:
    metadata:
      labels:
        app: mealdb-app
    spec:
      containers:
      - name: mealdb-app
        image: mealdb-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mealdb-service
spec:
  selector:
    app: mealdb-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer